name: atcho
description: Atcho Chwiya Reward App for stores to promote their products to clients using Augmented Reality Technolgy in an interactive way.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  styled_widget: ^0.4.1
  flutter_hooks: ^0.18.5+1
  motion_toast: ^2.6.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  easy_localization: ^3.0.2
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.12
  animations: ^2.0.7
  flutter_svg: ^2.0.9

  # maps
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.0

  # ar plugin
  ar_flutter_plugin: ^0.7.3
  arcore_flutter_plugin: ^0.1.0

  # Websocket
  web_socket_channel: ^2.4.0

  # Media Service
  image_picker: ^1.0.2

  # Architecture
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0

  # notifications
  flutter_local_notifications: ^15.1.1
  workmanager: ^0.5.1

  # Navigation
  auto_route: ^5.0.4

  # Injection
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  injectable_generator: ^2.1.3
  stacked_generator: ^1.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/3d/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf